FROM alpine:latest
MAINTAINER "Ashish Singh" <afiffing@gmail.com>

RUN set -ex && \
    buildDeps="python-dev build-base libffi-dev openssl-dev" && \
    apk add --no-cache $buildDeps python py-pip ca-certificates bash && \
    pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir ansible && \
    apk del --purge $buildDeps

CMD ["ansible"]
